version: "3"

volumes:
  mongodb_volume:

services:
  mongo_service:
    build: MongoService/
    restart: always
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017

  web_service:
    build: WebService/
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
    ports:
      - 27017:27017